# Generated by Django 4.2.11 on 2024-03-09 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Countries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=100, verbose_name='country')),
                ('msg', models.CharField(max_length=100, verbose_name='country')),
                ('name', models.CharField(max_length=100, verbose_name='country')),
                ('capital', models.CharField(max_length=100, verbose_name='country')),
                ('iso3', models.CharField(max_length=3, verbose_name='country')),
            ],
        ),
    ]
