# Generated by Django 4.2.11 on 2024-03-09 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paises', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='countries',
            name='capital',
            field=models.CharField(max_length=100, verbose_name='capital'),
        ),
        migrations.AlterField(
            model_name='countries',
            name='iso3',
            field=models.CharField(max_length=3, verbose_name='iso3'),
        ),
        migrations.AlterField(
            model_name='countries',
            name='msg',
            field=models.CharField(max_length=100, verbose_name='msg'),
        ),
        migrations.AlterField(
            model_name='countries',
            name='name',
            field=models.CharField(max_length=100, verbose_name='name'),
        ),
    ]
