# Generated by Django 4.2.11 on 2024-03-09 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paises', '0002_alter_countries_capital_alter_countries_iso3_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='countries',
            name='country',
        ),
        migrations.AddField(
            model_name='countries',
            name='iso2',
            field=models.CharField(max_length=3, null=True, verbose_name='iso2'),
        ),
    ]
