# Generated by Django 4.2.11 on 2024-03-09 17:06

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('paises', '0003_remove_countries_country_countries_iso2'),
    ]

    operations = [
        migrations.AddField(
            model_name='countries',
            name='data',
            field=jsonfield.fields.JSONField(default=dict, verbose_name='data'),
        ),
    ]
