# Generated by Django 4.2.11 on 2024-03-09 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paises', '0004_countries_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='countries',
            name='error',
            field=models.BooleanField(default=False, verbose_name='error'),
        ),
    ]
